name: Deploy to Firebase

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          REACT_APP_BASE_URL: "https://kichirmichir-dev.web.app"
          REACT_APP_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: "kichirmichir-dev"
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_KEY }}
